### PR TITLE
Fix skylake installation jobscript

### LINKED ISSUE #8: installjob_skylake.sh broken
When submitting a job to skylake nodes, I get this error:

`sbatch: error: Batch job submission failed: Requested node configuration is not available`

Probably something to do with removing the vulture nodes, I'm guessing that

`#SBATCH constraint=12cores`

needs to be removed.

### PR DESCRIPTION
**Pull request by FokkeDijkstra**
The only Skylake based machines left are the V100 GPU nodes. This change will select these for the software installation job.

### CODE REVIEW

**Comment by FokkeDijkstra** [comment]
This fixes #8

File: jobscripts/peregrine/installjob_skylake.sh [hunk 1]
```diff
@@ -4,8 +4,8 @@
 #SBATCH --cpus-per-task=2
 #SBATCH --mem=64G
```
Comment (bedroge) [inline jobscripts/peregrine/installjob_skylake.sh]: Should we also just request all the cores+mem?

Comment (camarocico) [reply jobscripts/peregrine/installjob_skylake.sh]: Yes, there are 12 cores on the V100s, right?

**Review by camarocico — CHANGES_REQUESTED** [review]
Let's also change
```
#SBATCH --cpus-per-task=2
#SBATCH --mem=64G
```

to

```
#SBATCH --cpus-per-task=12
#SBATCH --mem=128G
```

**Comment by FokkeDijkstra** [comment]
128GB memory would be too much, I think.
There was an explicit ``--tasks-per-node`` and ``--cpus-per-task`` setting to distinguish MPI from threaded applications. 
I think MPI testing needs a non-zero ``--tasks-per-node`` setting to work properly. 
The existing values were a compromise by setting both to non-zero. I am not sure that is really helpful. Since MPI might need ``--tasks-per-node`` we should then probably only set that.
What do you think?

**Comment by camarocico** [comment]
Memory isn't that important above 32 or 64, I think. As for MPI, we can increase the `--cpus-per-task` to 3, so that, with `--tasks-per-node=4` we take all 12 cores.

**Review by camarocico — APPROVED** [review]

**Comment by FokkeDijkstra** [comment]
I've updated the file to request all available CPU cores (4 tasks and 3 cores per task)  and 120GB of memory.
